import { createZipBuffer } from '../zip';
import { FileTree } from '../generators/file-tree';

interface GitFile {
  path: string;
  content: string;
}

interface GitHubContentResponse {
  content: { sha: string };
  commit: { sha: string };
}

export class GitHubPushService {
  private apiBase = 'https://api.github.com';

  private async request(
    token: string,
    method: string,
    path: string,
    body?: unknown
  ): Promise<any> {
    const res = await fetch(`${this.apiBase}${path}`, {
      method,
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: 'application/vnd.github+json',
        'Content-Type': 'application/json',
      },
      body: body ? JSON.stringify(body) : undefined,
    });
    if (!res.ok) {
      const err = await res.json().catch(() => ({ message: res.statusText }));
      throw new Error(`GitHub API error: ${err.message}`);
    }
    return res.json();
  }

  async initializeRepo(
    token: string,
    owner: string,
    repo: string
  ): Promise<void> {
    try {
      await this.request(
        token,
        'GET',
        `/repos/${owner}/${repo}/contents/README.md`
      );
    } catch {
      await this.request(
        token,
        'PUT',
        `/repos/${owner}/${repo}/contents/README.md`,
        {
          message: 'Initialize SUKIT export',
          content: Buffer.from('# SUKIT App\n\nGenerated by SUKIT\n').toString(
            'base64'
          ),
        }
      );
    }
  }

  async pushFiles(
    token: string,
    owner: string,
    repo: string,
    files: GitFile[],
    branch: string = 'main',
    message: string = 'Update from SUKIT'
  ): Promise<void> {
    const existingShas = await this.getExistingFiles(
      token,
      owner,
      repo,
      branch
    );
    const batchSize = 100;

    for (let i = 0; i < files.length; i += batchSize) {
      const batch = files.slice(i, i + batchSize);
      await this.createOrUpdateFiles(
        token,
        owner,
        repo,
        batch,
        existingShas,
        branch,
        message
      );
    }
  }

  async createBranch(
    token: string,
    owner: string,
    repo: string,
    branchName: string,
    sourceBranch: string = 'main'
  ): Promise<void> {
    const ref = await this.request(
      token,
      'GET',
      `/repos/${owner}/${repo}/git/refs/heads/${sourceBranch}`
    );
    await this.request(token, 'POST', `/repos/${owner}/${repo}/git/refs`, {
      ref: `refs/heads/${branchName}`,
      sha: ref.object.sha,
    });
  }

  async createPullRequest(
    token: string,
    owner: string,
    repo: string,
    title: string,
    body: string,
    branch: string,
    base: string = 'main'
  ): Promise<number> {
    const pr = await this.request(
      token,
      'POST',
      `/repos/${owner}/${repo}/pulls`,
      {
        title,
        body,
        head: branch,
        base,
      }
    );
    return pr.number;
  }

  async getLatestCommitSha(
    token: string,
    owner: string,
    repo: string,
    branch: string
  ): Promise<string> {
    const ref = await this.request(
      token,
      'GET',
      `/repos/${owner}/${repo}/git/refs/heads/${branch}`
    );
    return ref.object.sha;
  }

  async createTreeFromFiles(
    token: string,
    owner: string,
    repo: string,
    files: GitFile[],
    baseTreeSha: string
  ): Promise<string> {
    const tree = await this.request(
      token,
      'POST',
      `/repos/${owner}/${repo}/git/trees`,
      {
        base_tree: baseTreeSha,
        tree: files.map((f) => ({
          path: f.path,
          mode: '100644',
          type: 'blob',
          content: f.content,
        })),
      }
    );
    return tree.sha;
  }

  async createCommit(
    token: string,
    owner: string,
    repo: string,
    message: string,
    treeSha: string,
    parentSha: string
  ): Promise<string> {
    const commit = await this.request(
      token,
      'POST',
      `/repos/${owner}/${repo}/git/commits`,
      {
        message,
        tree: treeSha,
        parents: [parentSha],
      }
    );
    return commit.sha;
  }

  async updateBranch(
    token: string,
    owner: string,
    repo: string,
    branch: string,
    commitSha: string
  ): Promise<void> {
    await this.request(
      token,
      'PATCH',
      `/repos/${owner}/${repo}/git/refs/heads/${branch}`,
      {
        sha: commitSha,
        force: false,
      }
    );
  }

  private async getExistingFiles(
    token: string,
    owner: string,
    repo: string,
    branch: string
  ): Promise<Map<string, string>> {
    const shas = new Map<string, string>();
    try {
      const tree = await this.request(
        token,
        'GET',
        `/repos/${owner}/${repo}/git/trees/${branch}?recursive=1`
      );
      for (const item of tree.tree || []) {
        if (item.type === 'blob') shas.set(item.path, item.sha);
      }
    } catch {}
    return shas;
  }

  private async createOrUpdateFiles(
    token: string,
    owner: string,
    repo: string,
    files: GitFile[],
    existingShas: Map<string, string>,
    branch: string,
    message: string
  ): Promise<void> {
    const latestSha = await this.getLatestCommitSha(token, owner, repo, branch);
    const treeSha = await this.createTreeFromFiles(
      token,
      owner,
      repo,
      files,
      latestSha
    );
    const commitSha = await this.createCommit(
      token,
      owner,
      repo,
      message,
      treeSha,
      latestSha
    );
    await this.updateBranch(token, owner, repo, branch, commitSha);
  }
}

export const pushService = new GitHubPushService();
