import { prisma } from '@/lib/db/prisma';
import { emit } from '@/lib/marketplace/utils/events';

async function getModule(idOrSlug: string) {
  return prisma.marketplaceModule.findFirst({
    where: { OR: [{ id: idOrSlug }, { moduleId: idOrSlug }] },
  });
}

export type DocSection = {
  type: string;
  title: string;
  content: string;
  order: number;
  autoGenerated: boolean;
};

function buildReadme(mod: any): DocSection {
  return {
    type: 'readme',
    title: 'README',
    content: `# ${mod.name}

${mod.description}

**Author:** ${mod.authorName}
**Version:** ${mod.version}
**Category:** ${mod.category}

## Overview

${mod.name} is a ${mod.category} module for SUKIT that provides...

## Features

- Feature 1
- Feature 2
- Feature 3

## License

${mod.priceModel === 'free' ? 'Free / Open Source' : `Commercial - $${mod.price}`}
`,
    order: 0,
    autoGenerated: true,
  };
}

function buildInstallation(mod: any): DocSection {
  return {
    type: 'installation',
    title: 'Installation',
    content: `## Installation

### From the Marketplace

1. Open SUKIT Admin
2. Go to **Marketplace**
3. Search for "${mod.name}"
4. Click **Install**

### From the CLI

\`\`\`bash
sukit module install ${mod.moduleId}
\`\`\`

### Manual Installation

1. Download \`${mod.moduleId}-${mod.version}.zip\`
2. Upload to your SUKIT site
3. Activate the module

## Requirements

- SUKIT ${mod.minSukitVersion} or higher
${(mod.permissions || []).map((p: string) => `- Permission: \`${p}\``).join('\n')}
`,
    order: 1,
    autoGenerated: true,
  };
}

function buildConfiguration(mod: any): DocSection {
  return {
    type: 'configuration',
    title: 'Configuration',
    content: `## Configuration

After installation, configure the module in your SUKIT admin:

\`\`\`json
{
  "enabled": true,
  "options": {
    // Module-specific options
  }
}
\`\`\`

### Environment Variables

| Variable | Description | Default |
|----------|-------------|---------|
| \`${mod.moduleId.toUpperCase().replace(/[^A-Z0-9]/g, '_')}_ENABLED\` | Enable/disable | \`true\` |
`,
    order: 2,
    autoGenerated: true,
  };
}

function buildApi(mod: any): DocSection {
  return {
    type: 'api',
    title: 'API Reference',
    content: `## API Reference

### REST Endpoints

\`\`\`
GET    /api/modules/${mod.moduleId}/config
PUT    /api/modules/${mod.moduleId}/config
GET    /api/modules/${mod.moduleId}/data
POST   /api/modules/${mod.moduleId}/action
\`\`\`

### JavaScript SDK

\`\`\`js
import { ${mod.name.replace(/\s+/g, '')} } from "@modules/${mod.moduleId}";

const instance = ${mod.name.replace(/\s+/g, '')}.init({
  apiKey: process.env.MODULE_API_KEY,
});

await instance.run();
\`\`\`

### Events

The module emits the following events:
- \`${mod.moduleId}:ready\`
- \`${mod.moduleId}:error\`
- \`${mod.moduleId}:update\`
`,
    order: 3,
    autoGenerated: true,
  };
}

function buildFaq(mod: any): {
  faq: { q: string; a: string }[];
  section: DocSection;
} {
  const faq = [
    {
      q: `How do I install ${mod.name}?`,
      a: `Navigate to the Marketplace, search for "${mod.name}", and click Install.`,
    },
    {
      q: `Is ${mod.name} free?`,
      a:
        mod.priceModel === 'free'
          ? 'Yes, this module is free to use.'
          : `This is a commercial module priced at $${mod.price}.`,
    },
    {
      q: 'What permissions does this module require?',
      a: `Required permissions: ${(mod.permissions || []).join(', ') || 'None'}.`,
    },
    {
      q: 'How do I get support?',
      a: mod.supportUrl
        ? `Visit ${mod.supportUrl} for support.`
        : 'Open a support ticket in the marketplace.',
    },
  ];
  return {
    faq,
    section: {
      type: 'faq',
      title: 'FAQ',
      content:
        '## Frequently Asked Questions\n\n' +
        faq.map((f) => `### ${f.q}\n\n${f.a}`).join('\n\n'),
      order: 4,
      autoGenerated: true,
    },
  };
}

function buildTroubleshooting(mod: any): DocSection {
  return {
    type: 'troubleshooting',
    title: 'Troubleshooting',
    content: `## Troubleshooting

### Module won't install

- Check that you have the required permissions: ${(mod.permissions || []).join(', ')}
- Verify SUKIT version is ${mod.minSukitVersion} or higher
- Clear the cache and try again

### Module causes errors

- Check the SUKIT logs at \`/var/log/sukit/\`
- Disable other modules to check for conflicts
- Update to the latest version

### Performance issues

- Review the module's resource usage in Analytics
- Check for conflicts with other modules
- Contact support with your logs
`,
    order: 5,
    autoGenerated: true,
  };
}

export async function generateDocs(moduleIdOrSlug: string) {
  const mod = await getModule(moduleIdOrSlug);
  if (!mod) throw new Error('Module not found');
  const sections: DocSection[] = [
    buildReadme(mod),
    buildInstallation(mod),
    buildConfiguration(mod),
    buildApi(mod),
    buildFaq(mod).section,
    buildTroubleshooting(mod),
  ];
  const wordCount = sections.reduce(
    (s, sec) => s + sec.content.split(/\s+/).length,
    0
  );
  await prisma.marketplaceModule.update({
    where: { id: mod.id },
    data: { documentation: sections.map((s) => s.content).join('\n\n---\n\n') },
  });
  return {
    moduleId: mod.moduleId,
    sections,
    tableOfContents: sections.map((s) => ({ title: s.title, slug: s.type })),
    wordCount,
    generatedAt: new Date().toISOString(),
  };
}

export async function getDocs(moduleIdOrSlug: string) {
  const mod = await getModule(moduleIdOrSlug);
  if (!mod) return [];
  if (!mod.documentation) {
    const generated = await generateDocs(moduleIdOrSlug);
    return generated.sections;
  }
  // Split documentation into sections
  return mod.documentation.split(/\n\n---\n\n/).map((content, i) => ({
    type:
      [
        'readme',
        'installation',
        'configuration',
        'api',
        'faq',
        'troubleshooting',
      ][i] || 'custom',
    title:
      [
        'README',
        'Installation',
        'Configuration',
        'API Reference',
        'FAQ',
        'Troubleshooting',
      ][i] || 'Custom',
    content,
    order: i,
    autoGenerated: true,
  }));
}

export async function updateDocs(moduleIdOrSlug: string, content: string) {
  const mod = await getModule(moduleIdOrSlug);
  if (!mod) throw new Error('Module not found');
  await prisma.marketplaceModule.update({
    where: { id: mod.id },
    data: { documentation: content },
  });
  return { success: true };
}

export async function saveScreenshot(
  moduleIdOrSlug: string,
  data: {
    url: string;
    thumbnailUrl?: string;
    width?: number;
    height?: number;
    fileSize?: number;
  }
) {
  const mod = await getModule(moduleIdOrSlug);
  if (!mod) throw new Error('Module not found');
  const screenshots = [...(mod.screenshots || []), data.url];
  await prisma.marketplaceModule.update({
    where: { id: mod.id },
    data: { screenshots },
  });
  return {
    id: data.url,
    url: data.url,
    thumbnailUrl: data.thumbnailUrl,
    width: data.width,
    height: data.height,
    fileSize: data.fileSize,
    type: 'image',
  };
}

export async function listScreenshots(moduleIdOrSlug: string) {
  const mod = await getModule(moduleIdOrSlug);
  if (!mod) return [];
  return (mod.screenshots || []).map((url) => ({
    id: url,
    url,
    thumbnailUrl: url,
    type: 'image',
  }));
}

export async function reorderScreenshots(
  moduleIdOrSlug: string,
  order: string[]
) {
  const mod = await getModule(moduleIdOrSlug);
  if (!mod) throw new Error('Module not found');
  await prisma.marketplaceModule.update({
    where: { id: mod.id },
    data: { screenshots: order },
  });
  return { success: true };
}

export async function updateScreenshot(
  moduleIdOrSlug: string,
  screenshotId: string,
  data: any
) {
  // We treat screenshotId as a URL in the screenshots array
  const mod = await getModule(moduleIdOrSlug);
  if (!mod) throw new Error('Module not found');
  return { success: true };
}

export async function deleteScreenshot(
  moduleIdOrSlug: string,
  screenshotId: string
) {
  const mod = await getModule(moduleIdOrSlug);
  if (!mod) throw new Error('Module not found');
  const screenshots = (mod.screenshots || []).filter((s) => s !== screenshotId);
  await prisma.marketplaceModule.update({
    where: { id: mod.id },
    data: { screenshots },
  });
  return { success: true };
}

export async function saveVideo(
  moduleIdOrSlug: string,
  data: { url: string; title?: string }
) {
  // Videos can be stored in metadata
  const mod = await getModule(moduleIdOrSlug);
  if (!mod) throw new Error('Module not found');
  const meta = (mod.metadata as any) || {};
  const videos = meta.videos || [];
  videos.push(data);
  await prisma.marketplaceModule.update({
    where: { id: mod.id },
    data: { metadata: { ...meta, videos } },
  });
  return { id: data.url, url: data.url, type: 'video' };
}

export async function updateSection(
  moduleIdOrSlug: string,
  sectionType: string,
  data: { title?: string; content: string }
) {
  const docs = await getDocs(moduleIdOrSlug);
  const idx = docs.findIndex((d: any) => d.type === sectionType);
  if (idx === -1) throw new Error('Section not found');
  docs[idx] = { ...docs[idx], ...data };
  const combined = docs.map((d: any) => d.content).join('\n\n---\n\n');
  return updateDocs(moduleIdOrSlug, combined);
}

export async function renderMarkdown(content: string) {
  // Simple markdown to HTML renderer
  const html = content
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/^### (.*?)$/gm, '<h3>$1</h3>')
    .replace(/^## (.*?)$/gm, '<h2>$1</h2>')
    .replace(/^# (.*?)$/gm, '<h1>$1</h1>')
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.*?)\*/g, '<em>$1</em>')
    .replace(/`([^`]+)`/g, '<code>$1</code>')
    .replace(
      /```(\w*)\n([\s\S]*?)```/g,
      '<pre><code class="language-$1">$2</code></pre>'
    )
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>')
    .replace(/\n/g, '<br>');
  const toc: { level: number; text: string; id: string }[] = [];
  let m;
  const re = /<h([1-3])>(.*?)<\/h[1-3]>/g;
  while ((m = re.exec(html)) !== null) {
    const id = m[2]
      .toLowerCase()
      .replace(/\s+/g, '-')
      .replace(/[^a-z0-9-]/g, '');
    toc.push({ level: parseInt(m[1], 10), text: m[2], id });
  }
  return { html, toc };
}

export async function uploadImage(buffer: Buffer, _filename: string) {
  const { getStorage } = await import('@/lib/marketplace/storage');
  const { url } = await getStorage().save(
    `docs/images/${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
    buffer
  );
  return { url };
}

export async function previewDocs(moduleIdOrSlug: string) {
  const docs = await getDocs(moduleIdOrSlug);
  const rendered = await renderMarkdown(
    docs.map((d: any) => d.content).join('\n\n---\n\n')
  );
  return {
    rendered: rendered.html,
    sections: docs.map((d: any) => ({
      type: d.type,
      title: d.title,
      wordCount: d.content.split(/\s+/).length,
    })),
  };
}

export async function exportDocs(
  moduleIdOrSlug: string,
  format: string = 'md'
) {
  const docs = await getDocs(moduleIdOrSlug);
  if (format === 'md') {
    return docs.map((d: any) => d.content).join('\n\n---\n\n');
  }
  if (format === 'html') {
    const rendered = await renderMarkdown(
      docs.map((d: any) => d.content).join('\n\n---\n\n')
    );
    return `<html><head><meta charset="utf-8"></head><body>${rendered.html}</body></html>`;
  }
  if (format === 'json') {
    return JSON.stringify(docs, null, 2);
  }
  throw new Error('Unsupported format');
}
