import type { SukitKernel } from '@sukit/core';
import type { FileDescriptor, CommandResult } from '../../types';

interface GitHubRepo {
  id: number;
  name: string;
  fullName: string;
  cloneUrl: string;
  htmlUrl: string;
  defaultBranch: string;
}
interface GitHubPR {
  number: number;
  htmlUrl: string;
  state: string;
  title: string;
}
interface GitHubBranch {
  name: string;
  sha: string;
  protected: boolean;
}

export class GitHubIntegration {
  private kernel: SukitKernel;
  private token: string = '';
  private apiBase = 'https://api.github.com';

  constructor(kernel: SukitKernel) {
    this.kernel = kernel;
  }

  setToken(token: string) {
    this.token = token;
  }

  isAuthenticated(): boolean {
    return !!this.token;
  }

  async getAuthUrl(redirectUri: string): Promise<string> {
    const clientId = process.env.GITHUB_CLIENT_ID || '';
    return `https://github.com/login/oauth/authorize?client_id=${clientId}&redirect_uri=${encodeURIComponent(redirectUri)}&scope=repo,user`;
  }

  async authenticate(
    code: string
  ): Promise<{ accessToken: string; user: any }> {
    const res = await fetch('https://github.com/login/oauth/access_token', {
      method: 'POST',
      headers: {
        Accept: 'application/json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        client_id: process.env.GITHUB_CLIENT_ID,
        client_secret: process.env.GITHUB_CLIENT_SECRET,
        code,
      }),
    });
    const data = await res.json();
    this.token = data.access_token;
    const userRes = await this.ghFetch('/user');
    const user = await userRes.json();
    return { accessToken: data.access_token, user };
  }

  async createRepo(
    name: string,
    description: string,
    isPrivate = false
  ): Promise<GitHubRepo> {
    const res = await this.ghFetch('/user/repos', {
      method: 'POST',
      body: JSON.stringify({
        name,
        description,
        private: isPrivate,
        auto_init: true,
        license_template: 'mit',
      }),
    });
    return res.json();
  }

  async getRepo(fullName: string): Promise<GitHubRepo | null> {
    const res = await this.ghFetch(`/repos/${fullName}`);
    if (!res.ok) return null;
    return res.json();
  }

  async listRepos(): Promise<GitHubRepo[]> {
    const res = await this.ghFetch('/user/repos?per_page=100&sort=updated');
    return res.json();
  }

  async pushSite(
    siteId: string,
    repoName: string,
    branch = 'main'
  ): Promise<CommandResult> {
    const site = await this.kernel.sites.get(siteId);
    const pages = await this.kernel.pages.list(siteId);
    const owner = await this.getCurrentUser();

    let repo = await this.getRepo(`${owner}/${repoName}`);
    if (!repo)
      repo = await this.createRepo(
        repoName,
        `Site "${site.name}" generated by SUKIT`
      );

    const files = this.buildSiteFiles(site, pages);
    const ref = await this.getRef(repo.fullName, `heads/${branch}`);

    if (!ref) {
      const masterRef = await this.getRef(repo.fullName, 'heads/master');
      if (masterRef)
        await this.createBranch(repo.fullName, branch, masterRef.object.sha);
    }

    const latestSha =
      ref?.object.sha ||
      (await this.getRef(repo.fullName, 'heads/master'))?.object.sha;
    const treeItems = files.map((f) => ({
      path: f.path,
      mode: '100644' as const,
      type: 'blob' as const,
      content: f.content.toString(),
    }));
    const treeRes = await this.ghFetch(`/repos/${repo.fullName}/git/trees`, {
      method: 'POST',
      body: JSON.stringify({
        tree: treeItems,
        base_tree: latestSha || undefined,
      }),
    });
    const tree = await treeRes.json();
    const commitRes = await this.ghFetch(
      `/repos/${repo.fullName}/git/commits`,
      {
        method: 'POST',
        body: JSON.stringify({
          message: `Update site "${site.name}"`,
          tree: tree.sha,
          parents: latestSha ? [latestSha] : [],
        }),
      }
    );
    const commit = await commitRes.json();
    await this.ghFetch(`/repos/${repo.fullName}/git/refs/heads/${branch}`, {
      method: 'PATCH',
      body: JSON.stringify({ sha: commit.sha }),
    });

    return {
      success: true,
      message: `Site pushed to ${repo.fullName}`,
      data: {
        repo: repo.fullName,
        branch,
        commit: commit.sha,
        files: files.length,
      },
    };
  }

  async createPR(
    repoFullName: string,
    title: string,
    body: string,
    head: string,
    base = 'main'
  ): Promise<GitHubPR> {
    const res = await this.ghFetch(`/repos/${repoFullName}/pulls`, {
      method: 'POST',
      body: JSON.stringify({ title, body, head, base }),
    });
    return res.json();
  }

  async listPRs(
    repoFullName: string,
    state: 'open' | 'closed' | 'all' = 'open'
  ): Promise<GitHubPR[]> {
    const res = await this.ghFetch(
      `/repos/${repoFullName}/pulls?state=${state}`
    );
    return res.json();
  }

  async listBranches(repoFullName: string): Promise<GitHubBranch[]> {
    const res = await this.ghFetch(`/repos/${repoFullName}/branches`);
    return res.json();
  }

  async createBranch(
    repoFullName: string,
    branchName: string,
    sha: string
  ): Promise<void> {
    await this.ghFetch(`/repos/${repoFullName}/git/refs`, {
      method: 'POST',
      body: JSON.stringify({ ref: `refs/heads/${branchName}`, sha }),
    });
  }

  async getCommitHistory(
    repoFullName: string
  ): Promise<{ sha: string; message: string; author: string; date: string }[]> {
    const res = await this.ghFetch(
      `/repos/${repoFullName}/commits?per_page=20`
    );
    const commits = await res.json();
    return commits.map((c: any) => ({
      sha: c.sha,
      message: c.commit.message,
      author: c.commit.author.name,
      date: c.commit.author.date,
    }));
  }

  async createIssue(
    repoFullName: string,
    title: string,
    body: string,
    labels?: string[]
  ): Promise<any> {
    const res = await this.ghFetch(`/repos/${repoFullName}/issues`, {
      method: 'POST',
      body: JSON.stringify({ title, body, labels }),
    });
    return res.json();
  }

  async enableActions(repoFullName: string): Promise<void> {
    const workflow = Buffer.from(
      `
name: Deploy SUKIT Site
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci && npm run build
      - run: npm run export
    `
    ).toString('base64');

    await this.ghFetch(
      `/repos/${repoFullName}/contents/.github/workflows/deploy.yml`,
      {
        method: 'PUT',
        body: JSON.stringify({
          message: 'Add GitHub Actions deploy workflow',
          content: workflow,
        }),
      }
    );
  }

  private async getRef(
    repo: string,
    ref: string
  ): Promise<{ ref: string; object: { sha: string; type: string } } | null> {
    const res = await this.ghFetch(`/repos/${repo}/git/refs/${ref}`);
    if (!res.ok) return null;
    return res.json();
  }

  private async getCurrentUser(): Promise<string> {
    const res = await this.ghFetch('/user');
    const user = await res.json();
    return user.login;
  }

  private async ghFetch(
    path: string,
    options?: RequestInit
  ): Promise<Response> {
    return fetch(`${this.apiBase}${path}`, {
      ...options,
      headers: {
        Authorization: `Bearer ${this.token}`,
        Accept: 'application/vnd.github.v3+json',
        'Content-Type': 'application/json',
        ...options?.headers,
      },
    });
  }

  private buildSiteFiles(site: any, pages: any[]): FileDescriptor[] {
    return [
      {
        path: 'package.json',
        content: JSON.stringify({
          name: site.name,
          version: '1.0.0',
          private: true,
          scripts: { build: 'sukit build', export: 'sukit export' },
        }),
      },
      {
        path: 'sukit.config.json',
        content: JSON.stringify(
          { siteId: site.id, domain: site.domain },
          null,
          2
        ),
      },
      {
        path: 'README.md',
        content: `# ${site.name}\n\nSite generated by SUKIT.\n`,
      },
      ...pages.map((page, i) => ({
        path: `pages/${page.slug || `page-${i}`}.json`,
        content: JSON.stringify(page, null, 2),
      })),
    ];
  }
}
