'use client';

import { useState } from 'react';
import type { DocumentSection, DocSectionType, ScreenshotData } from '../types';

interface DocumentationEditorProps {
  sections: DocumentSection[];
  screenshots: ScreenshotData[];
  moduleName: string;
  onSave: (sections: DocumentSection[]) => Promise<void>;
  onGenerate: (sectionType: DocSectionType) => Promise<void>;
  onUploadScreenshot: (file: File, caption?: string) => Promise<ScreenshotData>;
  onReorderScreenshots: (ids: string[]) => Promise<void>;
  onDeleteScreenshot: (id: string) => Promise<void>;
  onRenderMarkdown: (md: string) => Promise<{ html: string; toc: any[] }>;
  saving?: boolean;
}

const sectionLabels: Record<DocSectionType, string> = {
  readme: 'README',
  installation: 'Installation',
  configuration: 'Configuration',
  api: 'API Reference',
  blocks: 'Blocks',
  faq: 'FAQ',
  troubleshooting: 'Troubleshooting',
};

export function DocumentationEditor({
  sections,
  screenshots,
  moduleName,
  onSave,
  onGenerate,
  onUploadScreenshot,
  onReorderScreenshots,
  onDeleteScreenshot,
  onRenderMarkdown,
  saving,
}: DocumentationEditorProps) {
  const [activeSection, setActiveSection] = useState<DocSectionType>('readme');
  const [editContent, setEditContent] = useState('');
  const [preview, setPreview] = useState(false);
  const [previewHtml, setPreviewHtml] = useState('');
  const [showGenerateMenu, setShowGenerateMenu] = useState(false);
  const [dragIndex, setDragIndex] = useState<number | null>(null);

  const currentSection = sections.find((s) => s.type === activeSection);
  const displayedContent = editContent || currentSection?.content || '';

  async function handlePreview() {
    if (!preview) {
      const result = await onRenderMarkdown(displayedContent);
      setPreviewHtml(result.html);
    }
    setPreview(!preview);
  }

  async function handleSave() {
    const updated = sections.map((s) =>
      s.type === activeSection ? { ...s, content: editContent } : s
    );
    const exists = updated.some((s) => s.type === activeSection);
    if (!exists) {
      updated.push({
        type: activeSection,
        title: sectionLabels[activeSection],
        content: editContent,
        order: sections.length,
        autoGenerated: false,
      });
    }
    await onSave(updated);
  }

  return (
    <div className="flex gap-6">
      <div className="w-56 flex-shrink-0">
        <h3 className="text-sm font-semibold text-gray-900 mb-3">Sections</h3>
        <div className="space-y-1">
          {(Object.keys(sectionLabels) as DocSectionType[]).map((type) => {
            const sec = sections.find((s) => s.type === type);
            return (
              <button
                key={type}
                onClick={() => {
                  setActiveSection(type);
                  setEditContent(sec?.content || '');
                  setPreview(false);
                }}
                className={`w-full text-left px-3 py-2 text-sm rounded-md transition-colors ${activeSection === type ? 'bg-indigo-50 text-indigo-700 font-medium' : 'text-gray-600 hover:bg-gray-50'}`}
              >
                <span className="block truncate">{sectionLabels[type]}</span>
                {sec && (
                  <span
                    className={`text-xs ${sec.autoGenerated ? 'text-gray-400' : 'text-indigo-400'}`}
                  >
                    {sec.autoGenerated ? 'Auto' : 'Custom'}
                  </span>
                )}
              </button>
            );
          })}
        </div>

        <div className="mt-4">
          <button
            onClick={() => setShowGenerateMenu(!showGenerateMenu)}
            className="w-full px-3 py-2 text-sm border border-gray-300 rounded-md hover:bg-gray-50"
          >
            + Generate Section
          </button>
          {showGenerateMenu && (
            <div className="mt-1 bg-white border rounded-lg shadow-sm">
              {(Object.keys(sectionLabels) as DocSectionType[]).map((type) => (
                <button
                  key={type}
                  onClick={() => {
                    onGenerate(type);
                    setShowGenerateMenu(false);
                  }}
                  className="w-full text-left px-3 py-2 text-sm hover:bg-gray-50 first:rounded-t-lg last:rounded-b-lg"
                >
                  {sectionLabels[type]}
                </button>
              ))}
            </div>
          )}
        </div>

        <div className="mt-6">
          <h3 className="text-sm font-semibold text-gray-900 mb-3">
            Screenshots ({screenshots.length})
          </h3>
          {screenshots.length === 0 ? (
            <p className="text-xs text-gray-500">No screenshots</p>
          ) : (
            <div className="space-y-2">
              {screenshots.map((ss, i) => (
                <div
                  key={ss.id}
                  className="flex items-center gap-2 bg-gray-50 rounded-lg p-2 cursor-move"
                  draggable
                  onDragStart={() => setDragIndex(i)}
                  onDragOver={(e) => e.preventDefault()}
                  onDrop={() => {
                    if (dragIndex !== null) {
                      const ids = screenshots.map((s) => s.id);
                      const [moved] = ids.splice(dragIndex, 1);
                      ids.splice(i, 0, moved);
                      onReorderScreenshots(ids);
                      setDragIndex(null);
                    }
                  }}
                >
                  <img
                    src={ss.thumbnailUrl}
                    alt=""
                    className="w-10 h-8 rounded object-cover"
                  />
                  <div className="flex-1 min-w-0">
                    <p className="text-xs truncate">
                      {ss.caption || `Screenshot ${i + 1}`}
                    </p>
                  </div>
                  <button
                    onClick={() => onDeleteScreenshot(ss.id)}
                    className="text-xs text-red-500 hover:text-red-700"
                  >
                    &times;
                  </button>
                </div>
              ))}
            </div>
          )}
          <label className="mt-2 flex items-center justify-center px-3 py-2 border-2 border-dashed border-gray-300 rounded-lg text-xs text-gray-500 cursor-pointer hover:border-indigo-400">
            + Add Screenshot
            <input
              type="file"
              accept="image/*"
              className="hidden"
              onChange={async (e) => {
                const file = e.target.files?.[0];
                if (file) await onUploadScreenshot(file);
              }}
            />
          </label>
        </div>
      </div>

      <div className="flex-1">
        <div className="flex items-center justify-between mb-3">
          <h3 className="text-sm font-semibold text-gray-900">
            {sectionLabels[activeSection]}
          </h3>
          <div className="flex gap-2">
            <button
              onClick={handlePreview}
              className="px-3 py-1.5 text-xs border border-gray-300 rounded-md hover:bg-gray-50"
            >
              {preview ? 'Edit' : 'Preview'}
            </button>
            <button
              onClick={handleSave}
              disabled={saving}
              className="px-3 py-1.5 text-xs bg-indigo-600 text-white rounded-md hover:bg-indigo-700 disabled:opacity-50"
            >
              {saving ? 'Saving...' : 'Save Section'}
            </button>
          </div>
        </div>

        {preview ? (
          <div
            className="min-h-[400px] bg-white border border-gray-200 rounded-lg p-4 prose prose-sm max-w-none"
            dangerouslySetInnerHTML={{ __html: previewHtml }}
          />
        ) : (
          <textarea
            value={displayedContent}
            onChange={(e) => setEditContent(e.target.value)}
            placeholder={`Write ${sectionLabels[activeSection]} documentation in Markdown...`}
            className="w-full min-h-[400px] px-4 py-3 border border-gray-200 rounded-lg text-sm font-mono focus:ring-2 focus:ring-indigo-500 resize-y"
          />
        )}
      </div>
    </div>
  );
}
