import { FileTree } from './file-tree';
import {
  ReactViteGenerator,
  type FrontendOptions,
  type PageData,
  type SiteData,
} from './frontend';
import { ExpressPrismaGenerator, type ModuleInfo } from './backend';

export interface FullStackOptions {
  frontend: FrontendOptions;
}

export class FullStackGenerator {
  async generate(
    site: SiteData,
    pages: PageData[],
    modules: ModuleInfo[],
    options: FullStackOptions
  ): Promise<FileTree> {
    const tree = new FileTree();

    const frontendGen = new ReactViteGenerator();
    const frontendFiles = await frontendGen.generate(
      site,
      pages,
      options.frontend
    );
    for (const f of frontendFiles.getAll()) {
      tree.add(`frontend/${f.path}`, f.content);
    }

    const backendGen = new ExpressPrismaGenerator();
    const backendFiles = await backendGen.generate(site.name, modules);
    for (const f of backendFiles.getAll()) {
      tree.add(`backend/${f.path}`, f.content);
    }

    tree.add('docker-compose.yml', this.dockerCompose());
    tree.add('docker-compose.prod.yml', this.dockerComposeProd());
    tree.add('.gitignore', this.gitignore());
    tree.add('README.md', this.readme(site));
    tree.add('LICENSE', this.license());
    tree.add('README.md', this.readme(site));
    tree.add('LICENSE', this.license());

    return tree;
  }

  private dockerCompose(): string {
    return `services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://app:password@postgres:5432/app
      JWT_SECRET: change-this-in-production
      CORS_ORIGIN: http://localhost:5173
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "npx prisma generate && npx prisma db push && npm run dev"

volumes:
  postgres_data:
`;
  }

  private dockerComposeProd(): string {
    return `services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: \${DB_USER:-app}
      POSTGRES_PASSWORD: \${DB_PASSWORD}
      POSTGRES_DB: \${DB_NAME:-app}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "\${API_PORT:-3001}:3001"
    environment:
      DATABASE_URL: postgresql://\${DB_USER}:\${DB_PASSWORD}@postgres:5432/\${DB_NAME}
      JWT_SECRET: \${JWT_SECRET}
      CORS_ORIGIN: \${FRONTEND_URL}
      NODE_ENV: production
    restart: always
    depends_on:
      - postgres

volumes:
  postgres_data:
`;
  }

  private gitignore(): string {
    return `node_modules/
dist/
.next/
.env
.env.local
*.log
.DS_Store
.cache/
.turbo/
coverage/
.vscode/
.idea/
`;
  }

  private deployWorkflow(): string {
    return `name: Deploy

on:
  push:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npx prisma generate
      - run: npm run build
      - run: echo "Deploy your app to Railway, Render, Fly.io, or your own server"
`;
  }

  private readme(site: SiteData): string {
    const slug = site.name.toLowerCase().replace(/\s+/g, '-');
    return `# ${site.name}

A full-stack application generated by **SUKIT**.

**Stack:** React + TypeScript + Vite (frontend) · Express + Prisma + PostgreSQL (backend)

## Project Structure

\`\`\`
├── frontend/               # React + Vite + TypeScript
│   ├── pages/              # Page components from visual design
│   ├── components/         # Block components
│   ├── lib/                # API client
│   ├── package.json
│   └── vite.config.ts
├── backend/                # Express + Prisma + TypeScript
│   ├── src/routes/         # API routes (auth, forms, etc.)
│   ├── src/middleware/      # Auth, error handling
│   ├── prisma/schema.prisma
│   └── package.json
├── docker-compose.yml      # Development setup
└── README.md
\`\`\`

## Quick Start

### Prerequisites

- Node.js 20+
- Docker & Docker Compose (for database)

### Development

\`\`\`bash
# 1. Start PostgreSQL
docker compose up -d postgres

# 2. Install dependencies
npm install

# 3. Setup database
npx prisma generate
npx prisma db push
npx prisma db seed

# 4. Start backend (runs on :3001)
npm run dev
\`\`\`

In another terminal:

\`\`\`bash
# 5. Start frontend (runs on :5173, proxies API to :3001)
npm run dev:frontend
\`\`\`

Open **http://localhost:5173** for the app, **http://localhost:3001/api/health** for the API.

### One-Command Setup

\`\`\`bash
docker compose up -d
\`\`\`

This starts PostgreSQL and the backend.

### Production

\`\`\`bash
docker compose -f docker-compose.prod.yml up -d
\`\`\`

## API Endpoints

| Method | Path | Auth | Description |
|--------|------|------|-------------|
| GET | /api/health | No | Health check |
| POST | /api/auth/register | No | Create account |
| POST | /api/auth/login | No | Login |
| GET | /api/auth/me | Yes | Current user |
| POST | /api/forms/:id/submit | No | Submit form data |
| GET | /api/forms/:id/submissions | Yes | View submissions |

## Deployment

The app can be deployed anywhere Node.js and PostgreSQL are supported:

- **Frontend**: Vercel, Netlify, Cloudflare Pages
- **Backend**: Railway, Render, Fly.io, DigitalOcean
- **Database**: Supabase, Neon, Railway, AWS RDS

## Tech Stack

| Layer | Technology |
|-------|-----------|
| Frontend | React 19, Vite 6, TypeScript, Tailwind CSS |
| Backend | Express 5, TypeScript |
| Database | PostgreSQL 16, Prisma ORM |
| Auth | JWT (bcryptjs) |
| API Client | Fetch + React Query |
| Container | Docker & Docker Compose |
| CI/CD | GitHub Actions |
`;
  }

  private license(): string {
    return `MIT License

Copyright (c) ${new Date().getFullYear()}

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files...
`;
  }
}
